HOTKEY_MODIFIER_SCANCODE = 0x1D
HOTKEY_TRIGGER_SCANCODE = 0x10
HOTKEY_TEXT = "SC01D + SC010"

MAX_CLIP_ITEMS = 500
POPUP_SETTINGS_KEY = "popup_window"
SETTINGS_WINDOW_SETTINGS_KEY = "settings_window"
CLIP_HISTORY_FILE = "clipboard_history.txt"
CLIP_IMAGES_DIR = "clipboard_images"
DEFAULT_CLIP_TAB_NAME = "Буфер"
DEFAULT_IMAGE_TAB_NAME = "Фото"
